tripincar/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.index, name='index'),
    path('order/<int:pk>/', views.order_detail, name='order_detail'),
    path('order_edit/<int:pk>/', views.order_edit, name='order_edit'),
    path('in-airport/', views.order_create_in_airport, name='order_create_in_airport'),
    path('in-city/', views.order_create_in_city, name='order_create_in_city'),
    path('order_list/', views.order_list, name='order_list'),
    path('order_delete/<int:pk>/', views.order_delete, name='order_delete'),

]

tripincar/tripincar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')), 
    path('', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

tripincar/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('profile/<str:username>/', views.profile, name='profile'),

    path('auth/signup/', views.SignUp.as_view(), name='signup'),

    path(
      'auth/logout/',
      auth_views.LogoutView.as_view(
        template_name='users/logged_out.html'),
        name='logout'
    ),    
    
    path('auth/login/', auth_views.LoginView.as_view(
        template_name='users/login.html'), name='login'),

    path('auth/password_change/', auth_views.PasswordChangeView.as_view(
        template_name='users/password_change_form.html'),
        name='password_change'),
    path('auth/password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),

    path('auth/password_reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset_form.html'),
        name='password_reset'),
    path('auth/password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path('auth/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('auth/reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete')
]

tripincar/templates/includes/footer.html
<footer class="border-top text-center py-3 fixed-bottom bg-white">
  <p>© {{ year }} Copyright <span style="color:red">Trip</span>InCar</p>    
</footer>

tripincar/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'orders:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Trip</span>InCar
    </a>
    <button class="navbar-toggler"
            type="button" 
            data-toggle="collapse" 
            data-target="#navbarNav" 
            aria-controls="navbarNav" 
            aria-expanded="false" 
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav nav-tabs">
        <li class="nav-item active">
          <a class="nav-link {% if view_name  == 'orders:tariffs' %}active{% endif %}"
            href="">Тарифы</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'orders:order_create_in_airport' %}active{% endif %}"
            href="{% url 'orders:order_create_in_airport' %}">Заказать в аэропорт</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'orders:order_create_in_city' %}active{% endif %}"
            href="{% url 'orders:order_create_in_city' %}">Заказать из аэропорта</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:profile' %}active{% endif %}"
            href="{% url 'users:profile' request.user.username %}">Мои заказы</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:password_change' %}active{% endif %}"
            href="{% url 'users:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}"
            href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" >Пользователь: {{ user.username }}</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}"
            href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}"
            href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</header>
{% endwith %}