tripincar/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.index, name='index'),
    path('order/<int:pk>/', views.order_detail, name='order_detail'),
    path('order_edit/<int:pk>/', views.order_edit, name='order_edit'),
    path('in-airport/', views.order_create_in_airport, name='order_create_in_airport'),
    path('in-city/', views.order_create_in_city, name='order_create_in_city'),
    path('order_list/', views.order_list, name='order_list'),
    path('order_delete/<int:pk>/', views.order_delete, name='order_delete'),

]

tripincar/tripincar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')), 
    path('', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

tripincar/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('profile/<str:username>/', views.profile, name='profile'),

    path('auth/signup/', views.SignUp.as_view(), name='signup'),

    path(
      'auth/logout/',
      auth_views.LogoutView.as_view(
        template_name='users/logged_out.html'),
        name='logout'
    ),    
    
    path('auth/login/', auth_views.LoginView.as_view(
        template_name='users/login.html'), name='login'),

    path('auth/password_change/', auth_views.PasswordChangeView.as_view(
        template_name='users/password_change_form.html'),
        name='password_change'),
    path('auth/password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),

    path('auth/password_reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset_form.html'),
        name='password_reset'),
    path('auth/password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path('auth/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('auth/reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete')
]

tripincar/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core import validators
from django.db import models
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField


class UserRole:
    USER = 'user'
    DRIVER = 'driver'
    ADMIN = 'admin'


class User(AbstractUser):
    ROLES = (
        (UserRole.USER, 'USER'),
        (UserRole.DRIVER, 'DRIVER'),
        (UserRole.ADMIN, 'ADMIN')
    )
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_(
            'Required. 150 characters or fewer.'
            'Letters, digits and @/./+/-/_ only.'
        ),
        validators=[validators.RegexValidator(regex=r'^[\w.@+-]+\Z')],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    email = models.EmailField(
        _('email'),
        max_length=254,
        unique=True,
    )
    
    telephone = PhoneNumberField(
        _('phone'),
        region='RU'
    )

    role = models.CharField(
        _('role'),
        max_length=9,
        choices=ROLES,
        default=UserRole.USER
    )

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ('id',)
        constraints = [
            models.UniqueConstraint(
                fields=['username', 'email'],
                name='unique_name'
            ),
        ]

    def __str__(self):
        return self.username

    @property
    def is_admin(self):
        return (self.role == UserRole.ADMIN
                or self.is_staff
                or self.is_superuser)

    @property
    def is_user(self):
        return self.role == UserRole.USER

    @property
    def is_driver(self):
        return self.role == UserRole.DRIVER

tripincar/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()

class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'telephone', 'email')

tripincar/users/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404, render

# Импортируем CreateView, чтобы создать ему наследника
from django.views.generic import CreateView

# Функция reverse_lazy позволяет получить URL по параметрам функции path()
# Берём, тоже пригодится
from django.urls import reverse_lazy

# Импортируем класс формы, чтобы сослаться на неё во view-классе
from .forms import CreationForm

User = get_user_model()


class SignUp(CreateView):
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('orders:index')
    template_name = 'users/signup.html'


def profile(request, username):
    """Обработчик страницы автора."""
    author = get_object_or_404(User, username=username)
    orders = author.orders.all()

    template = 'users/profile.html'
    context = {
        'orders_user': orders,
        'username': author,
    }
    return render(request, template_name=template, context=context)

tripincar/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём вас снова!
          </p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

tripincar/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

tripincar/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Пароль изменён
          </div>
          <div class="card-body"> 
            <p>Пароль изменён успешно</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

tripincar/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Изменить пароль
          </div>
          <div class="card-body">
            <form method="post" action="{% url 'users:password_change' %}">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_old_password">
                  Старый пароль
                  <span class="required text-danger">*</span>
                </label>    
                <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password1">
                  Новый пароль
                  <span class="required text-danger">*</span>
                </label>    
                <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                  <small id="id_new_password1-help" class="form-text text-muted">
                    <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                  </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password2">
                  Подтверждение нового пароля
                  <span class="required text-danger">*</span>
                </label>    
                <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Изменить пароль
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

tripincar/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Восстановление пароля завершено
          </div>
          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="{% url 'users:login' %}">войти</a>
          </div> 
        </div> 
      </div>
    </div> 
  </div>
{% endblock %}

tripincar/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
  <div class="container py-5"> 
    {% if validlink %}
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Введите новый пароль
            </div>
            <div class="card-body">
              <form method="post">
                {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_new_password1">
                    Новый пароль        
                    <span class="required text-danger">*</span>        
                  </label>    
                  <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                  <small id="id_new_password1-help" class="form-text text-muted">
                    <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                  </small>      
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_new_password2">
                    Подтверждение нового пароля        
                    <span class="required text-danger">*</span>        
                  </label>    
                  <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
                </div>
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-primary">
                    Назначить новый пароль
                  </button>
                </div>
              </form>
            </div> <!-- card body -->
          </div> <!-- card -->
        </div> <!-- col -->
      </div> <!-- row -->
    {% else %}
    <!-- если использована неправильная ссылка -->
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Ошибка
            </div>
            <div class="card-body">
              <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
            </div> <!-- card body -->
          </div> <!-- card -->
        </div> <!-- col -->
      </div> <!-- row -->
    {% endif %}
  </div>
{% endblock %}

tripincar/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Отправлено письмо
          </div>
          <div class="card-body">
            <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
          </div> 
        </div> 
      </div>
    </div> 
  </div>
{% endblock %}

tripincar/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
          </div>
          <div class="card-body"> 
            <form method="post" action="{% url 'users:password_reset' %}">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_email">
                  Адрес электронной почты
                  <span class="required text-danger">*</span>
                </label>    
                <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Сбросить пароль
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>  
  </div>
{% endblock %}

tripincar/templates/users/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ username }}
{% endblock %}
{% block content %}
  <main>
    <div class="container py-5 mb-5">
      <h1>Все заказы пользователя {{ username }}</h1>
      <h3>Всего заказов: {{ orders_user|length }}</h3>
      <article>
        {% for order in orders_user %}
          <ul>
            <li>Заказ: {{ order }}</li>
            <li>Автор: {{ username }}</li>
            <li>Дата публикации: {{ order.pub_date|date:"d E Y" }}</li>
          </ul>
          <p>
            <a href="{% url 'orders:order_detail' order.pk %}">
              Подробная информация
            </a>
          </p>
          {% if order.author == user %}
            <a href="{% url 'orders:order_edit' order.pk %}">
              <button type="button" class="btn btn-success btn-sm">
                Редактировать
              </button>
            </a>
            <a href="{% url 'orders:order_delete' order.pk %}">
              <button type="button" class="btn btn-danger btn-sm">
                Отменить заказ
              </button>
            </a>
          {% endif %}
        {% endfor %}
      </article>
    </div>
  </main>
{% endblock %}

tripincar/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}